modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="fd"
version="0.24.01.1"
displayName="FNaF's: Build & Decor (Java Edition) - Snapshot"
displayURL="https://hirxs-website.nett"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Hirx's | Hirxs_mc"
description="Have you ever wanted to replicate a restaurant from FNAF but in Minecraft?"

[[dependencies.fd]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.fd]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

