modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="fd"
version="0.24.02.1"
displayName="FNaF's: Build & Decor (Java Edition) - Snapshot"
displayURL="https://hirxs-website.net"
logoFile="logo.png"
credits="By FB&D Team"
authors="Hirx's | Hirxs_mc"
description="Have you ever wanted to replicate a restaurant from FNAF but in Minecraft?"

[[dependencies.fd]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.fd]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0]"
    ordering="NONE"
    side="BOTH"


[[dependencies.fd]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

