modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="fd"
version="0.23.07.1"
displayName="FNaFs Decorations (Java Edition) - Snapshot"
displayURL="https://hirxs-web.weebly.com/"
logoFile="logo.png"
credits="Hyru,Chill's,Cheez & Mura"
authors="Hirx's | Hirxs_mc"
description="Have you ever wanted to replicate a restaurant from FNAF but in Minecraft?"

[[dependencies.fd]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




