
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fnafsdecorationsport.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import net.mcreator.fnafsdecorationsport.item.ChangertoolItem;
import net.mcreator.fnafsdecorationsport.FdMod;

public class FdModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, FdMod.MODID);
	public static final RegistryObject<Item> FNAF_1WALLUP = block(FdModBlocks.FNAF_1WALLUP);
	public static final RegistryObject<Item> FNAF_1WALLDECO_1 = block(FdModBlocks.FNAF_1WALLDECO_1);
	public static final RegistryObject<Item> FNAF_1WALLDECO_2 = block(FdModBlocks.FNAF_1WALLDECO_2);
	public static final RegistryObject<Item> FNAFWALLMIDDLE_2 = block(FdModBlocks.FNAFWALLMIDDLE_2);
	public static final RegistryObject<Item> FNAF_1WALLMIDDLE_1 = block(FdModBlocks.FNAF_1WALLMIDDLE_1);
	public static final RegistryObject<Item> F_NA_F_1WALLMIDDLE_3 = block(FdModBlocks.F_NA_F_1WALLMIDDLE_3);
	public static final RegistryObject<Item> FNAF_1WALLMIDDLE_4 = block(FdModBlocks.FNAF_1WALLMIDDLE_4);
	public static final RegistryObject<Item> FNAF_1WALLMIDDLE_5 = block(FdModBlocks.FNAF_1WALLMIDDLE_5);
	public static final RegistryObject<Item> FNAF_1WALLDOWN_1 = block(FdModBlocks.FNAF_1WALLDOWN_1);
	public static final RegistryObject<Item> F_NA_F_1WALLDOWN_2 = block(FdModBlocks.F_NA_F_1WALLDOWN_2);
	public static final RegistryObject<Item> FNAF_1WALLBATHROOM = block(FdModBlocks.FNAF_1WALLBATHROOM);
	public static final RegistryObject<Item> FNAF_1WALLBATHROOM_2 = block(FdModBlocks.FNAF_1WALLBATHROOM_2);
	public static final RegistryObject<Item> FNAF_1WALLBATHROOM_3 = block(FdModBlocks.FNAF_1WALLBATHROOM_3);
	public static final RegistryObject<Item> STAGEUP = block(FdModBlocks.STAGEUP);
	public static final RegistryObject<Item> STAGEMIDDLE_1 = block(FdModBlocks.STAGEMIDDLE_1);
	public static final RegistryObject<Item> STAGETILES = block(FdModBlocks.STAGETILES);
	public static final RegistryObject<Item> STAGETILES_2 = block(FdModBlocks.STAGETILES_2);
	public static final RegistryObject<Item> STAGETILES_3 = block(FdModBlocks.STAGETILES_3);
	public static final RegistryObject<Item> STAGEDOWN = block(FdModBlocks.STAGEDOWN);
	public static final RegistryObject<Item> STAGEBLOCK_4 = block(FdModBlocks.STAGEBLOCK_4);
	public static final RegistryObject<Item> STAGEBLOCK_1 = block(FdModBlocks.STAGEBLOCK_1);
	public static final RegistryObject<Item> STAGEBLOCK_2 = block(FdModBlocks.STAGEBLOCK_2);
	public static final RegistryObject<Item> STAGEBLOCK_3 = block(FdModBlocks.STAGEBLOCK_3);
	public static final RegistryObject<Item> FNAF_2WALLUP_2 = block(FdModBlocks.FNAF_2WALLUP_2);
	public static final RegistryObject<Item> FNAF_2WALLUP_1 = block(FdModBlocks.FNAF_2WALLUP_1);
	public static final RegistryObject<Item> FNAF_2WALLMIDDLE_3 = block(FdModBlocks.FNAF_2WALLMIDDLE_3);
	public static final RegistryObject<Item> FNAF_2WALLMIDDLE_2 = block(FdModBlocks.FNAF_2WALLMIDDLE_2);
	public static final RegistryObject<Item> FNAF_2WALLMIDDLE_1 = block(FdModBlocks.FNAF_2WALLMIDDLE_1);
	public static final RegistryObject<Item> FNAF_2WALLDOWN_1 = block(FdModBlocks.FNAF_2WALLDOWN_1);
	public static final RegistryObject<Item> WHITEROOF = block(FdModBlocks.WHITEROOF);
	public static final RegistryObject<Item> ROOF_1 = block(FdModBlocks.ROOF_1);
	public static final RegistryObject<Item> ROOF_2 = block(FdModBlocks.ROOF_2);
	public static final RegistryObject<Item> FFDFLOOR = block(FdModBlocks.FFDFLOOR);
	public static final RegistryObject<Item> FLOORFFDSTAIRS = block(FdModBlocks.FLOORFFDSTAIRS);
	public static final RegistryObject<Item> FLOORFFDSLAB = block(FdModBlocks.FLOORFFDSLAB);
	public static final RegistryObject<Item> FLOORRED = block(FdModBlocks.FLOORRED);
	public static final RegistryObject<Item> FLOORREDSTAIRS = block(FdModBlocks.FLOORREDSTAIRS);
	public static final RegistryObject<Item> FLOORREDSLAB = block(FdModBlocks.FLOORREDSLAB);
	public static final RegistryObject<Item> FLOORBLUE = block(FdModBlocks.FLOORBLUE);
	public static final RegistryObject<Item> FLOORBLUESTAIRS = block(FdModBlocks.FLOORBLUESTAIRS);
	public static final RegistryObject<Item> FLOORBLUESLAB = block(FdModBlocks.FLOORBLUESLAB);
	public static final RegistryObject<Item> FLOORREDBLUE = block(FdModBlocks.FLOORREDBLUE);
	public static final RegistryObject<Item> FLOORREDNBLUESTAIRS = block(FdModBlocks.FLOORREDNBLUESTAIRS);
	public static final RegistryObject<Item> FLOORREDNBLUESLAB = block(FdModBlocks.FLOORREDNBLUESLAB);
	public static final RegistryObject<Item> FLOORWHITE = block(FdModBlocks.FLOORWHITE);
	public static final RegistryObject<Item> FLOORWHITESTAIRS = block(FdModBlocks.FLOORWHITESTAIRS);
	public static final RegistryObject<Item> FLOORWHITESLAB = block(FdModBlocks.FLOORWHITESLAB);
	public static final RegistryObject<Item> FFDINTERIORWALLUP = block(FdModBlocks.FFDINTERIORWALLUP);
	public static final RegistryObject<Item> FFDINTERIORWALLMIDDLE = block(FdModBlocks.FFDINTERIORWALLMIDDLE);
	public static final RegistryObject<Item> FFDINTERIORWALLTILES = block(FdModBlocks.FFDINTERIORWALLTILES);
	public static final RegistryObject<Item> FFDINTERIORWALLDOWN = block(FdModBlocks.FFDINTERIORWALLDOWN);
	public static final RegistryObject<Item> FFDEXTERIORWALLUP = block(FdModBlocks.FFDEXTERIORWALLUP);
	public static final RegistryObject<Item> FFDEXTERIORWALLMIDDLE = block(FdModBlocks.FFDEXTERIORWALLMIDDLE);
	public static final RegistryObject<Item> FFDEXTERIORWALLTILES = block(FdModBlocks.FFDEXTERIORWALLTILES);
	public static final RegistryObject<Item> FFDEXTERIORWALLDOWN = block(FdModBlocks.FFDEXTERIORWALLDOWN);
	public static final RegistryObject<Item> FNAFMOVIEWALLUPPEREXTERIOR = block(FdModBlocks.FNAFMOVIEWALLUPPEREXTERIOR);
	public static final RegistryObject<Item> FNAFMOVIEWALLUPPER_2EXTERIOR = block(FdModBlocks.FNAFMOVIEWALLUPPER_2EXTERIOR);
	public static final RegistryObject<Item> FNAFMOVIEWALLMIDDLE_2EXTERIOR = block(FdModBlocks.FNAFMOVIEWALLMIDDLE_2EXTERIOR);
	public static final RegistryObject<Item> FNAFMOVIEWALLMIDDLEEXTERIOR = block(FdModBlocks.FNAFMOVIEWALLMIDDLEEXTERIOR);
	public static final RegistryObject<Item> FNAFMOVIEWALLBOTTOMEXTERIOR = block(FdModBlocks.FNAFMOVIEWALLBOTTOMEXTERIOR);
	public static final RegistryObject<Item> REDARCADEFLOOR_1STAIRS = block(FdModBlocks.REDARCADEFLOOR_1STAIRS);
	public static final RegistryObject<Item> REDARCADEFLOOR_1SLAB = block(FdModBlocks.REDARCADEFLOOR_1SLAB);
	public static final RegistryObject<Item> BLUEARCADEFLOOR_1STAIRS = block(FdModBlocks.BLUEARCADEFLOOR_1STAIRS);
	public static final RegistryObject<Item> BLUEARCADEFLOOR_1SLAB = block(FdModBlocks.BLUEARCADEFLOOR_1SLAB);
	public static final RegistryObject<Item> CHANGERTOOL = REGISTRY.register("changertool", () -> new ChangertoolItem());
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKPURPLE = block(FdModBlocks.PIRATECOVECURTAINBLOCKPURPLE);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKBLUE = block(FdModBlocks.PIRATECOVECURTAINBLOCKBLUE);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKRED = block(FdModBlocks.PIRATECOVECURTAINBLOCKRED);
	public static final RegistryObject<Item> CURTAINPURPLEBLOCKPANEL = block(FdModBlocks.CURTAINPURPLEBLOCKPANEL);
	public static final RegistryObject<Item> CURTAINREDBLOCKPANEL = block(FdModBlocks.CURTAINREDBLOCKPANEL);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKPURPLEBLOCK = block(FdModBlocks.PIRATECOVECURTAINBLOCKPURPLEBLOCK);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKBLUEBLOCK = block(FdModBlocks.PIRATECOVECURTAINBLOCKBLUEBLOCK);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKREDBLOCK = block(FdModBlocks.PIRATECOVECURTAINBLOCKREDBLOCK);
	public static final RegistryObject<Item> CURTAINPURPLEBLOCK = block(FdModBlocks.CURTAINPURPLEBLOCK);
	public static final RegistryObject<Item> CURTAINREDBLOCK = block(FdModBlocks.CURTAINREDBLOCK);
	public static final RegistryObject<Item> ARCADEFLOOR_1 = block(FdModBlocks.ARCADEFLOOR_1);
	public static final RegistryObject<Item> REDARCADEFLOOR_1 = block(FdModBlocks.REDARCADEFLOOR_1);
	public static final RegistryObject<Item> PIZZERIALIGHTOFF = block(FdModBlocks.PIZZERIALIGHTOFF);
	public static final RegistryObject<Item> TRASH_1 = block(FdModBlocks.TRASH_1);
	public static final RegistryObject<Item> BLOCKGIFT = block(FdModBlocks.BLOCKGIFT);
	public static final RegistryObject<Item> WALLPAPERS = block(FdModBlocks.WALLPAPERS);
	public static final RegistryObject<Item> WALLPAPER_1 = block(FdModBlocks.WALLPAPER_1);
	public static final RegistryObject<Item> STARS_1 = block(FdModBlocks.STARS_1);
	public static final RegistryObject<Item> WALLSTRUCTURE = block(FdModBlocks.WALLSTRUCTURE);
	public static final RegistryObject<Item> STAGESPEAKER = block(FdModBlocks.STAGESPEAKER);
	public static final RegistryObject<Item> ROOFWIRES_1 = block(FdModBlocks.ROOFWIRES_1);
	public static final RegistryObject<Item> CURTAIN_1 = block(FdModBlocks.CURTAIN_1);
	public static final RegistryObject<Item> POSTER_1 = block(FdModBlocks.POSTER_1);
	public static final RegistryObject<Item> OFFICEWINDOW = block(FdModBlocks.OFFICEWINDOW);
	public static final RegistryObject<Item> OFFICEPOSTER = block(FdModBlocks.OFFICEPOSTER);
	public static final RegistryObject<Item> PIZZERIASIGNS_1 = block(FdModBlocks.PIZZERIASIGNS_1);
	public static final RegistryObject<Item> FLOORWIRES_1 = block(FdModBlocks.FLOORWIRES_1);
	public static final RegistryObject<Item> PARTYKIDSCHAIRBLUE = block(FdModBlocks.PARTYKIDSCHAIRBLUE);
	public static final RegistryObject<Item> PARTYKIDSCHAIRRED = block(FdModBlocks.PARTYKIDSCHAIRRED);
	public static final RegistryObject<Item> PARTYKIDSCHAIRBLACK = block(FdModBlocks.PARTYKIDSCHAIRBLACK);
	public static final RegistryObject<Item> PARTYKIDSCHAIRPURPLE = block(FdModBlocks.PARTYKIDSCHAIRPURPLE);
	public static final RegistryObject<Item> OFFICELAMP = block(FdModBlocks.OFFICELAMP);
	public static final RegistryObject<Item> STAGESUN = block(FdModBlocks.STAGESUN);
	public static final RegistryObject<Item> STAGECLOUDS = block(FdModBlocks.STAGECLOUDS);
	public static final RegistryObject<Item> PIRATECOVESIGN_1 = block(FdModBlocks.PIRATECOVESIGN_1);
	public static final RegistryObject<Item> SUPPLYROOMSHELVES = block(FdModBlocks.SUPPLYROOMSHELVES);
	public static final RegistryObject<Item> FANBLOCK = block(FdModBlocks.FANBLOCK);
	public static final RegistryObject<Item> FANBLOCKON = block(FdModBlocks.FANBLOCKON);
	public static final RegistryObject<Item> DESKPROPS = block(FdModBlocks.DESKPROPS);
	public static final RegistryObject<Item> ONLYOFFICEDESK = block(FdModBlocks.ONLYOFFICEDESK);
	public static final RegistryObject<Item> MONITORS_1 = block(FdModBlocks.MONITORS_1);
	public static final RegistryObject<Item> OFFICEDESK = block(FdModBlocks.OFFICEDESK);
	public static final RegistryObject<Item> OFFICECHAIR = block(FdModBlocks.OFFICECHAIR);
	public static final RegistryObject<Item> OFFICELIGHTOFF = block(FdModBlocks.OFFICELIGHTOFF);
	public static final RegistryObject<Item> OFFICEDOORBLOCKOPEN = block(FdModBlocks.OFFICEDOORBLOCKOPEN);
	public static final RegistryObject<Item> OFFICELIGHTBUTTONOFF = block(FdModBlocks.OFFICELIGHTBUTTONOFF);
	public static final RegistryObject<Item> OFFICEDOORBUTTONOFF = block(FdModBlocks.OFFICEDOORBUTTONOFF);
	public static final RegistryObject<Item> PARTYHATRED = block(FdModBlocks.PARTYHATRED);
	public static final RegistryObject<Item> WALLWARNINGSIGN = block(FdModBlocks.WALLWARNINGSIGN);
	public static final RegistryObject<Item> FAZSODARED = block(FdModBlocks.FAZSODARED);
	public static final RegistryObject<Item> FAZSODABLUE = block(FdModBlocks.FAZSODABLUE);
	public static final RegistryObject<Item> SHELF_1 = block(FdModBlocks.SHELF_1);
	public static final RegistryObject<Item> BLACKDOOR = doubleBlock(FdModBlocks.BLACKDOOR);
	public static final RegistryObject<Item> REDDOOR = doubleBlock(FdModBlocks.REDDOOR);
	public static final RegistryObject<Item> CHAIREXECUTION_SPAWN_EGG = REGISTRY.register("chairexecution_spawn_egg", () -> new ForgeSpawnEggItem(FdModEntities.CHAIREXECUTION, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> PIZZERIA_LIGHT_ON = block(FdModBlocks.PIZZERIA_LIGHT_ON);
	public static final RegistryObject<Item> CURTAIN_3 = block(FdModBlocks.CURTAIN_3);
	public static final RegistryObject<Item> CURTAIN_4 = block(FdModBlocks.CURTAIN_4);
	public static final RegistryObject<Item> CURTAIN_5 = block(FdModBlocks.CURTAIN_5);
	public static final RegistryObject<Item> WALLPAPERS_2 = block(FdModBlocks.WALLPAPERS_2);
	public static final RegistryObject<Item> WALLPAPERS_3 = block(FdModBlocks.WALLPAPERS_3);
	public static final RegistryObject<Item> STARS_2 = block(FdModBlocks.STARS_2);
	public static final RegistryObject<Item> STARS_3 = block(FdModBlocks.STARS_3);
	public static final RegistryObject<Item> MONITORS_2 = block(FdModBlocks.MONITORS_2);
	public static final RegistryObject<Item> MONITORS_3 = block(FdModBlocks.MONITORS_3);
	public static final RegistryObject<Item> MONITORS_4 = block(FdModBlocks.MONITORS_4);
	public static final RegistryObject<Item> GIFTBLUE = block(FdModBlocks.GIFTBLUE);
	public static final RegistryObject<Item> GIFTGREEN = block(FdModBlocks.GIFTGREEN);
	public static final RegistryObject<Item> GIFTYELLOW = block(FdModBlocks.GIFTYELLOW);
	public static final RegistryObject<Item> GIFTPURPLE = block(FdModBlocks.GIFTPURPLE);
	public static final RegistryObject<Item> ROOFWIRES_2 = block(FdModBlocks.ROOFWIRES_2);
	public static final RegistryObject<Item> ROOFWIRES_4 = block(FdModBlocks.ROOFWIRES_4);
	public static final RegistryObject<Item> ROOFWIRES_3 = block(FdModBlocks.ROOFWIRES_3);
	public static final RegistryObject<Item> ROOFWIRES_5 = block(FdModBlocks.ROOFWIRES_5);
	public static final RegistryObject<Item> CURTAIN_2 = block(FdModBlocks.CURTAIN_2);
	public static final RegistryObject<Item> TRASH_2 = block(FdModBlocks.TRASH_2);
	public static final RegistryObject<Item> TRASH_3 = block(FdModBlocks.TRASH_3);
	public static final RegistryObject<Item> OFFICEDOORBUTTONON = block(FdModBlocks.OFFICEDOORBUTTONON);
	public static final RegistryObject<Item> FLOORWIRES_2 = block(FdModBlocks.FLOORWIRES_2);
	public static final RegistryObject<Item> FLOORWIRES_3 = block(FdModBlocks.FLOORWIRES_3);
	public static final RegistryObject<Item> CURTAINRED_2BLOCK = block(FdModBlocks.CURTAINRED_2BLOCK);
	public static final RegistryObject<Item> CURTAINPURPLE_2BLOCK = block(FdModBlocks.CURTAINPURPLE_2BLOCK);
	public static final RegistryObject<Item> CURTAINRED_2BLOCKPANEL = block(FdModBlocks.CURTAINRED_2BLOCKPANEL);
	public static final RegistryObject<Item> CURTAINPURPLE_2BLOCKPANEL = block(FdModBlocks.CURTAINPURPLE_2BLOCKPANEL);
	public static final RegistryObject<Item> PIRATECOVESIGN_2 = block(FdModBlocks.PIRATECOVESIGN_2);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKRED_2 = block(FdModBlocks.PIRATECOVECURTAINBLOCKRED_2);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKRED_3 = block(FdModBlocks.PIRATECOVECURTAINBLOCKRED_3);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKPURPLE_2 = block(FdModBlocks.PIRATECOVECURTAINBLOCKPURPLE_2);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKPURPLE_3 = block(FdModBlocks.PIRATECOVECURTAINBLOCKPURPLE_3);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKBLUE_2 = block(FdModBlocks.PIRATECOVECURTAINBLOCKBLUE_2);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKBLUE_3 = block(FdModBlocks.PIRATECOVECURTAINBLOCKBLUE_3);
	public static final RegistryObject<Item> ARCADEFLOOR_2 = block(FdModBlocks.ARCADEFLOOR_2);
	public static final RegistryObject<Item> ARCADEFLOOR_3 = block(FdModBlocks.ARCADEFLOOR_3);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKREDBLOCK_2 = block(FdModBlocks.PIRATECOVECURTAINBLOCKREDBLOCK_2);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKBLUEBLOCK_2 = block(FdModBlocks.PIRATECOVECURTAINBLOCKBLUEBLOCK_2);
	public static final RegistryObject<Item> PIRATECOVECURTAINBLOCKPURPLEBLOCK_2 = block(FdModBlocks.PIRATECOVECURTAINBLOCKPURPLEBLOCK_2);
	public static final RegistryObject<Item> OFFICELIGHTBUTTONON = block(FdModBlocks.OFFICELIGHTBUTTONON);
	public static final RegistryObject<Item> OFFICEDOORBLOCK = block(FdModBlocks.OFFICEDOORBLOCK);
	public static final RegistryObject<Item> OFFICELIGHTON = block(FdModBlocks.OFFICELIGHTON);
	public static final RegistryObject<Item> PARTYHATGREEN = block(FdModBlocks.PARTYHATGREEN);
	public static final RegistryObject<Item> PARTYHATBLUE = block(FdModBlocks.PARTYHATBLUE);
	public static final RegistryObject<Item> PARTYHATPURPLE = block(FdModBlocks.PARTYHATPURPLE);
	public static final RegistryObject<Item> PIZZERIASIGNS_2 = block(FdModBlocks.PIZZERIASIGNS_2);
	public static final RegistryObject<Item> PIZZERIASIGNS_3 = block(FdModBlocks.PIZZERIASIGNS_3);
	public static final RegistryObject<Item> PIZZERIASIGNS_4 = block(FdModBlocks.PIZZERIASIGNS_4);
	public static final RegistryObject<Item> WALLPAPER_2 = block(FdModBlocks.WALLPAPER_2);
	public static final RegistryObject<Item> WALLPAPER_3 = block(FdModBlocks.WALLPAPER_3);
	public static final RegistryObject<Item> WALLPAPER_4 = block(FdModBlocks.WALLPAPER_4);
	public static final RegistryObject<Item> WALLPAPERS_4 = block(FdModBlocks.WALLPAPERS_4);
	public static final RegistryObject<Item> REDARCADEFLOOR_2 = block(FdModBlocks.REDARCADEFLOOR_2);
	public static final RegistryObject<Item> REDARCADEFLOOR_3 = block(FdModBlocks.REDARCADEFLOOR_3);
	public static final RegistryObject<Item> SHELF_2 = block(FdModBlocks.SHELF_2);
	public static final RegistryObject<Item> ALARM_CLOCK = block(FdModBlocks.ALARM_CLOCK);
	public static final RegistryObject<Item> ARCADE_SIGN = block(FdModBlocks.ARCADE_SIGN);
	public static final RegistryObject<Item> BLOOD_TRAIL = block(FdModBlocks.BLOOD_TRAIL);
	public static final RegistryObject<Item> CHICAS_MAGIC_RAINBOW = block(FdModBlocks.CHICAS_MAGIC_RAINBOW);
	public static final RegistryObject<Item> CHICAS_MAGIC_RAINBOW_2 = block(FdModBlocks.CHICAS_MAGIC_RAINBOW_2);
	public static final RegistryObject<Item> MAGIC_RAINBOW_3 = block(FdModBlocks.MAGIC_RAINBOW_3);
	public static final RegistryObject<Item> MAGICRAINBOW_4 = block(FdModBlocks.MAGICRAINBOW_4);
	public static final RegistryObject<Item> MAGURANBO_5 = block(FdModBlocks.MAGURANBO_5);
	public static final RegistryObject<Item> FNAF_2WALLMIDDLECONFETTI = block(FdModBlocks.FNAF_2WALLMIDDLECONFETTI);
	public static final RegistryObject<Item> PURPLESTAGEBRICKS = block(FdModBlocks.PURPLESTAGEBRICKS);
	public static final RegistryObject<Item> FNAF_2STAGEWALLMIDDLE = block(FdModBlocks.FNAF_2STAGEWALLMIDDLE);
	public static final RegistryObject<Item> FNAF_2STAGEWALLTILES = block(FdModBlocks.FNAF_2STAGEWALLTILES);
	public static final RegistryObject<Item> BALLOONS = block(FdModBlocks.BALLOONS);
	public static final RegistryObject<Item> BALLOONS_2 = block(FdModBlocks.BALLOONS_2);
	public static final RegistryObject<Item> BALLOONS_3 = block(FdModBlocks.BALLOONS_3);
	public static final RegistryObject<Item> BOBBLEHEADS = block(FdModBlocks.BOBBLEHEADS);
	public static final RegistryObject<Item> BIRTHDAY_CAKE = block(FdModBlocks.BIRTHDAY_CAKE);
	public static final RegistryObject<Item> EMERGENCY_LIGHT = block(FdModBlocks.EMERGENCY_LIGHT);
	public static final RegistryObject<Item> EMERGENCY_LIGHT_ON = block(FdModBlocks.EMERGENCY_LIGHT_ON);
	public static final RegistryObject<Item> WALLPOSTERFACESF = block(FdModBlocks.WALLPOSTERFACESF);
	public static final RegistryObject<Item> WALLPOSTERFACESC = block(FdModBlocks.WALLPOSTERFACESC);
	public static final RegistryObject<Item> WALLPOSTERFACESB = block(FdModBlocks.WALLPOSTERFACESB);
	public static final RegistryObject<Item> FFDWALLPOSTERFACES_1 = block(FdModBlocks.FFDWALLPOSTERFACES_1);
	public static final RegistryObject<Item> FFDWALLPOSTERFACES_2 = block(FdModBlocks.FFDWALLPOSTERFACES_2);
	public static final RegistryObject<Item> CHICAPLUSH = block(FdModBlocks.CHICAPLUSH);
	public static final RegistryObject<Item> CHICABETAPLUSH = block(FdModBlocks.CHICABETAPLUSH);
	public static final RegistryObject<Item> FREDDYPLUSH = block(FdModBlocks.FREDDYPLUSH);
	public static final RegistryObject<Item> BONNIEPLUSH = block(FdModBlocks.BONNIEPLUSH);
	public static final RegistryObject<Item> FOXYPLUSH = block(FdModBlocks.FOXYPLUSH);
	public static final RegistryObject<Item> SPRINGBONNIEPLUSH = block(FdModBlocks.SPRINGBONNIEPLUSH);
	public static final RegistryObject<Item> GOLDENFREDDYPLUSH = block(FdModBlocks.GOLDENFREDDYPLUSH);
	public static final RegistryObject<Item> FREDBEARPLUSH = block(FdModBlocks.FREDBEARPLUSH);
	public static final RegistryObject<Item> FNAFMOVIEOFFICEDOOR = doubleBlock(FdModBlocks.FNAFMOVIEOFFICEDOOR);
	public static final RegistryObject<Item> FNAFMOVIEBATHROOMDOOR = doubleBlock(FdModBlocks.FNAFMOVIEBATHROOMDOOR);
	public static final RegistryObject<Item> FFDPIZZERIADOOR = doubleBlock(FdModBlocks.FFDPIZZERIADOOR);
	public static final RegistryObject<Item> BATTINGTONFLOOR = block(FdModBlocks.BATTINGTONFLOOR);
	public static final RegistryObject<Item> BATTINGTONFLOOR_2 = block(FdModBlocks.BATTINGTONFLOOR_2);
	public static final RegistryObject<Item> BATTINGTONFLOOR_3 = block(FdModBlocks.BATTINGTONFLOOR_3);
	public static final RegistryObject<Item> BATTINGTONFLOOR_4 = block(FdModBlocks.BATTINGTONFLOOR_4);
	public static final RegistryObject<Item> BATTINGTONFLOOR_5 = block(FdModBlocks.BATTINGTONFLOOR_5);
	public static final RegistryObject<Item> BATTINGTONFLOOR_6 = block(FdModBlocks.BATTINGTONFLOOR_6);
	public static final RegistryObject<Item> BATTINGTONFLOOR_7 = block(FdModBlocks.BATTINGTONFLOOR_7);
	public static final RegistryObject<Item> SWITCHOFF = block(FdModBlocks.SWITCHOFF);
	public static final RegistryObject<Item> SWITCHON = block(FdModBlocks.SWITCHON);
	public static final RegistryObject<Item> FREDDY_FAZBEARTRASHCAN = block(FdModBlocks.FREDDY_FAZBEARTRASHCAN);
	public static final RegistryObject<Item> POLE_1 = block(FdModBlocks.POLE_1);
	public static final RegistryObject<Item> POLE_2 = block(FdModBlocks.POLE_2);

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
