
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.fnafsdecorationsport.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.fnafsdecorationsport.block.WoodenwallredsingleBlock;
import net.mcreator.fnafsdecorationsport.block.WoodenwallreddownBlock;
import net.mcreator.fnafsdecorationsport.block.WoodenwallbrowntopdirtyBlock;
import net.mcreator.fnafsdecorationsport.block.WoodenwallbrowntopBlock;
import net.mcreator.fnafsdecorationsport.block.WoodenwallbrowntilesBlock;
import net.mcreator.fnafsdecorationsport.block.WoodenwallbrownsingleBlock;
import net.mcreator.fnafsdecorationsport.block.WhiteroofBlock;
import net.mcreator.fnafsdecorationsport.block.WhiteblackfloorinvertedstairBlock;
import net.mcreator.fnafsdecorationsport.block.WhiteblackfloorinvertedslabBlock;
import net.mcreator.fnafsdecorationsport.block.WhiteblackfloorinvertedBlock;
import net.mcreator.fnafsdecorationsport.block.WallwarningsignBlock;
import net.mcreator.fnafsdecorationsport.block.WallstructureBlock;
import net.mcreator.fnafsdecorationsport.block.WallposterfacesfBlock;
import net.mcreator.fnafsdecorationsport.block.WallposterfacescBlock;
import net.mcreator.fnafsdecorationsport.block.WallposterfacesbBlock;
import net.mcreator.fnafsdecorationsport.block.WallpapersBlock;
import net.mcreator.fnafsdecorationsport.block.Wallpapers4Block;
import net.mcreator.fnafsdecorationsport.block.Wallpapers3Block;
import net.mcreator.fnafsdecorationsport.block.Wallpapers2Block;
import net.mcreator.fnafsdecorationsport.block.Wallpaper4Block;
import net.mcreator.fnafsdecorationsport.block.Wallpaper3Block;
import net.mcreator.fnafsdecorationsport.block.Wallpaper2Block;
import net.mcreator.fnafsdecorationsport.block.Wallpaper1Block;
import net.mcreator.fnafsdecorationsport.block.Trash3Block;
import net.mcreator.fnafsdecorationsport.block.Trash2Block;
import net.mcreator.fnafsdecorationsport.block.Trash1Block;
import net.mcreator.fnafsdecorationsport.block.TestingblockBlock;
import net.mcreator.fnafsdecorationsport.block.TablesouthBlock;
import net.mcreator.fnafsdecorationsport.block.TablenorthBlock;
import net.mcreator.fnafsdecorationsport.block.SwitchonBlock;
import net.mcreator.fnafsdecorationsport.block.SwitchoffBlock;
import net.mcreator.fnafsdecorationsport.block.SupplyroomshelvesBlock;
import net.mcreator.fnafsdecorationsport.block.Stars3Block;
import net.mcreator.fnafsdecorationsport.block.Stars2Block;
import net.mcreator.fnafsdecorationsport.block.Stars1Block;
import net.mcreator.fnafsdecorationsport.block.StageupBlock;
import net.mcreator.fnafsdecorationsport.block.StagetilesBlock;
import net.mcreator.fnafsdecorationsport.block.Stagetiles3Block;
import net.mcreator.fnafsdecorationsport.block.Stagetiles2Block;
import net.mcreator.fnafsdecorationsport.block.StagesunBlock;
import net.mcreator.fnafsdecorationsport.block.StagespeakerBlock;
import net.mcreator.fnafsdecorationsport.block.Stagemiddle1Block;
import net.mcreator.fnafsdecorationsport.block.StagedownBlock;
import net.mcreator.fnafsdecorationsport.block.StagecloudsBlock;
import net.mcreator.fnafsdecorationsport.block.Stageblock4Block;
import net.mcreator.fnafsdecorationsport.block.Stageblock3Block;
import net.mcreator.fnafsdecorationsport.block.Stageblock2Block;
import net.mcreator.fnafsdecorationsport.block.Stageblock1Block;
import net.mcreator.fnafsdecorationsport.block.SpringbonnieplushBlock;
import net.mcreator.fnafsdecorationsport.block.Shelf2Block;
import net.mcreator.fnafsdecorationsport.block.Shelf1Block;
import net.mcreator.fnafsdecorationsport.block.Roofwires5Block;
import net.mcreator.fnafsdecorationsport.block.Roofwires4Block;
import net.mcreator.fnafsdecorationsport.block.Roofwires3Block;
import net.mcreator.fnafsdecorationsport.block.Roofwires2Block;
import net.mcreator.fnafsdecorationsport.block.Roofwires1Block;
import net.mcreator.fnafsdecorationsport.block.Roof2Block;
import net.mcreator.fnafsdecorationsport.block.Roof1Block;
import net.mcreator.fnafsdecorationsport.block.ReddoorBlock;
import net.mcreator.fnafsdecorationsport.block.Redarcadefloor3Block;
import net.mcreator.fnafsdecorationsport.block.Redarcadefloor2Block;
import net.mcreator.fnafsdecorationsport.block.Redarcadefloor1stairsBlock;
import net.mcreator.fnafsdecorationsport.block.Redarcadefloor1slabBlock;
import net.mcreator.fnafsdecorationsport.block.Redarcadefloor1Block;
import net.mcreator.fnafsdecorationsport.block.PurplestagebricksBlock;
import net.mcreator.fnafsdecorationsport.block.Poster1Block;
import net.mcreator.fnafsdecorationsport.block.Pole2Block;
import net.mcreator.fnafsdecorationsport.block.Pole1Block;
import net.mcreator.fnafsdecorationsport.block.Pizzeriasigns4Block;
import net.mcreator.fnafsdecorationsport.block.Pizzeriasigns3Block;
import net.mcreator.fnafsdecorationsport.block.Pizzeriasigns2Block;
import net.mcreator.fnafsdecorationsport.block.Pizzeriasigns1Block;
import net.mcreator.fnafsdecorationsport.block.PizzerialightoffBlock;
import net.mcreator.fnafsdecorationsport.block.Pizzerialight1Block;
import net.mcreator.fnafsdecorationsport.block.Piratecovesign2Block;
import net.mcreator.fnafsdecorationsport.block.Piratecovesign1Block;
import net.mcreator.fnafsdecorationsport.block.PiratecovecurtainblockredblockBlock;
import net.mcreator.fnafsdecorationsport.block.Piratecovecurtainblockredblock2Block;
import net.mcreator.fnafsdecorationsport.block.PiratecovecurtainblockredBlock;
import net.mcreator.fnafsdecorationsport.block.Piratecovecurtainblockred3Block;
import net.mcreator.fnafsdecorationsport.block.Piratecovecurtainblockred2Block;
import net.mcreator.fnafsdecorationsport.block.PiratecovecurtainblockpurpleblockBlock;
import net.mcreator.fnafsdecorationsport.block.Piratecovecurtainblockpurpleblock2Block;
import net.mcreator.fnafsdecorationsport.block.PiratecovecurtainblockpurpleBlock;
import net.mcreator.fnafsdecorationsport.block.Piratecovecurtainblockpurple3Block;
import net.mcreator.fnafsdecorationsport.block.Piratecovecurtainblockpurple2Block;
import net.mcreator.fnafsdecorationsport.block.PiratecovecurtainblockblueblockBlock;
import net.mcreator.fnafsdecorationsport.block.Piratecovecurtainblockblueblock2Block;
import net.mcreator.fnafsdecorationsport.block.PiratecovecurtainblockblueBlock;
import net.mcreator.fnafsdecorationsport.block.Piratecovecurtainblockblue3Block;
import net.mcreator.fnafsdecorationsport.block.Piratecovecurtainblockblue2Block;
import net.mcreator.fnafsdecorationsport.block.PartykidschairredBlock;
import net.mcreator.fnafsdecorationsport.block.PartykidschairpurpleBlock;
import net.mcreator.fnafsdecorationsport.block.PartykidschairblueBlock;
import net.mcreator.fnafsdecorationsport.block.PartykidschairblackBlock;
import net.mcreator.fnafsdecorationsport.block.PartyhatredBlock;
import net.mcreator.fnafsdecorationsport.block.PartyhatpurpleBlock;
import net.mcreator.fnafsdecorationsport.block.PartyhatgreenBlock;
import net.mcreator.fnafsdecorationsport.block.PartyhatblueBlock;
import net.mcreator.fnafsdecorationsport.block.OnlyofficedeskBlock;
import net.mcreator.fnafsdecorationsport.block.OfficewindowBlock;
import net.mcreator.fnafsdecorationsport.block.OfficeposterBlock;
import net.mcreator.fnafsdecorationsport.block.OfficelightonBlock;
import net.mcreator.fnafsdecorationsport.block.OfficelightoffBlock;
import net.mcreator.fnafsdecorationsport.block.OfficelightbuttononBlock;
import net.mcreator.fnafsdecorationsport.block.OfficelightbuttonoffBlock;
import net.mcreator.fnafsdecorationsport.block.OfficelampBlock;
import net.mcreator.fnafsdecorationsport.block.OfficedoorbuttononBlock;
import net.mcreator.fnafsdecorationsport.block.OfficedoorbuttonoffBlock;
import net.mcreator.fnafsdecorationsport.block.OfficedoorblockopenBlock;
import net.mcreator.fnafsdecorationsport.block.OfficedoorblockBlock;
import net.mcreator.fnafsdecorationsport.block.OfficedeskBlock;
import net.mcreator.fnafsdecorationsport.block.OfficechairBlock;
import net.mcreator.fnafsdecorationsport.block.Monitors4Block;
import net.mcreator.fnafsdecorationsport.block.Monitors3Block;
import net.mcreator.fnafsdecorationsport.block.Monitors2Block;
import net.mcreator.fnafsdecorationsport.block.Monitors1Block;
import net.mcreator.fnafsdecorationsport.block.Maguranbo5Block;
import net.mcreator.fnafsdecorationsport.block.Magicrainbow4Block;
import net.mcreator.fnafsdecorationsport.block.MagicRainbow3Block;
import net.mcreator.fnafsdecorationsport.block.Largewallwires3Block;
import net.mcreator.fnafsdecorationsport.block.Largewallwires2Block;
import net.mcreator.fnafsdecorationsport.block.Largewallwires1Block;
import net.mcreator.fnafsdecorationsport.block.Largewallstars4Block;
import net.mcreator.fnafsdecorationsport.block.Largewallstars3Block;
import net.mcreator.fnafsdecorationsport.block.Largewallstars2Block;
import net.mcreator.fnafsdecorationsport.block.Largewallstars1Block;
import net.mcreator.fnafsdecorationsport.block.Largewallpartybanners3Block;
import net.mcreator.fnafsdecorationsport.block.Largewallpartybanners2Block;
import net.mcreator.fnafsdecorationsport.block.Largewallpartybanners1Block;
import net.mcreator.fnafsdecorationsport.block.Largewallpapercuts3Block;
import net.mcreator.fnafsdecorationsport.block.Largewallpapercuts2Block;
import net.mcreator.fnafsdecorationsport.block.Largewallpapercuts1Block;
import net.mcreator.fnafsdecorationsport.block.GoldenfreddyplushBlock;
import net.mcreator.fnafsdecorationsport.block.GiftyellowBlock;
import net.mcreator.fnafsdecorationsport.block.GiftpurpleBlock;
import net.mcreator.fnafsdecorationsport.block.GiftgreenBlock;
import net.mcreator.fnafsdecorationsport.block.GiftblueBlock;
import net.mcreator.fnafsdecorationsport.block.FreddyplushBlock;
import net.mcreator.fnafsdecorationsport.block.FreddyFazbeartrashcanBlock;
import net.mcreator.fnafsdecorationsport.block.FredbearplushBlock;
import net.mcreator.fnafsdecorationsport.block.FoxyplushBlock;
import net.mcreator.fnafsdecorationsport.block.Fnafwallmiddle2Block;
import net.mcreator.fnafsdecorationsport.block.FnafmoviewallupperexteriorBlock;
import net.mcreator.fnafsdecorationsport.block.Fnafmoviewallupper2exteriorBlock;
import net.mcreator.fnafsdecorationsport.block.FnafmoviewallmiddleexteriorBlock;
import net.mcreator.fnafsdecorationsport.block.Fnafmoviewallmiddle2exteriorBlock;
import net.mcreator.fnafsdecorationsport.block.FnafmoviewallbottomexteriorBlock;
import net.mcreator.fnafsdecorationsport.block.FnafmovieofficedoorBlock;
import net.mcreator.fnafsdecorationsport.block.FnafmoviebathroomdoorBlock;
import net.mcreator.fnafsdecorationsport.block.Fnaf2wallupperconfettiBlock;
import net.mcreator.fnafsdecorationsport.block.Fnaf2wallupperconfetti2Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf2wallup2Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf2wallup1Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf2wallmiddleconfettiBlock;
import net.mcreator.fnafsdecorationsport.block.Fnaf2wallmiddle3Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf2wallmiddle2Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf2wallmiddle1Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf2walldown1Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf2stagewalltilesBlock;
import net.mcreator.fnafsdecorationsport.block.Fnaf2stagewallmiddleBlock;
import net.mcreator.fnafsdecorationsport.block.Fnaf1wallupBlock;
import net.mcreator.fnafsdecorationsport.block.Fnaf1wallmiddle5Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf1wallmiddle4Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf1wallmiddle1Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf1walldown1Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf1walldeco2Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf1walldeco1Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf1wallbathroomBlock;
import net.mcreator.fnafsdecorationsport.block.Fnaf1wallbathroom3Block;
import net.mcreator.fnafsdecorationsport.block.Fnaf1wallbathroom2Block;
import net.mcreator.fnafsdecorationsport.block.FlooryellowbluestairBlock;
import net.mcreator.fnafsdecorationsport.block.FlooryellowblueslabBlock;
import net.mcreator.fnafsdecorationsport.block.FlooryellowblueBlock;
import net.mcreator.fnafsdecorationsport.block.Floorwires3Block;
import net.mcreator.fnafsdecorationsport.block.Floorwires2Block;
import net.mcreator.fnafsdecorationsport.block.Floorwires1Block;
import net.mcreator.fnafsdecorationsport.block.FloorwhitestairsBlock;
import net.mcreator.fnafsdecorationsport.block.FloorwhiteslabBlock;
import net.mcreator.fnafsdecorationsport.block.FloorwhiteBlock;
import net.mcreator.fnafsdecorationsport.block.FloorredstairsBlock;
import net.mcreator.fnafsdecorationsport.block.FloorredslabBlock;
import net.mcreator.fnafsdecorationsport.block.FloorrednbluestairsBlock;
import net.mcreator.fnafsdecorationsport.block.FloorrednblueslabBlock;
import net.mcreator.fnafsdecorationsport.block.FloorredblueBlock;
import net.mcreator.fnafsdecorationsport.block.FloorredBlock;
import net.mcreator.fnafsdecorationsport.block.FloorgreenbluestairBlock;
import net.mcreator.fnafsdecorationsport.block.FloorgreenblueslabBlock;
import net.mcreator.fnafsdecorationsport.block.FloorgreenblueBlock;
import net.mcreator.fnafsdecorationsport.block.FloorffdstairsBlock;
import net.mcreator.fnafsdecorationsport.block.FloorffdslabBlock;
import net.mcreator.fnafsdecorationsport.block.FloorbluestairsBlock;
import net.mcreator.fnafsdecorationsport.block.FloorblueslabBlock;
import net.mcreator.fnafsdecorationsport.block.FloorblueBlock;
import net.mcreator.fnafsdecorationsport.block.Ffdwallposterfaces2Block;
import net.mcreator.fnafsdecorationsport.block.Ffdwallposterfaces1Block;
import net.mcreator.fnafsdecorationsport.block.FfdpizzeriadoorBlock;
import net.mcreator.fnafsdecorationsport.block.FfdinteriorwallupBlock;
import net.mcreator.fnafsdecorationsport.block.FfdinteriorwalltilesBlock;
import net.mcreator.fnafsdecorationsport.block.Ffdinteriorwallmiddleconfetti3Block;
import net.mcreator.fnafsdecorationsport.block.Ffdinteriorwallmiddleconfetti2Block;
import net.mcreator.fnafsdecorationsport.block.Ffdinteriorwallmiddleconfetti1Block;
import net.mcreator.fnafsdecorationsport.block.FfdinteriorwallmiddleBlock;
import net.mcreator.fnafsdecorationsport.block.FfdinteriorwalldownBlock;
import net.mcreator.fnafsdecorationsport.block.FfdfloorBlock;
import net.mcreator.fnafsdecorationsport.block.FfdexteriorwallupBlock;
import net.mcreator.fnafsdecorationsport.block.FfdexteriorwalltilesBlock;
import net.mcreator.fnafsdecorationsport.block.FfdexteriorwallmiddleBlock;
import net.mcreator.fnafsdecorationsport.block.FfdexteriorwalldownBlock;
import net.mcreator.fnafsdecorationsport.block.FazsodaredBlock;
import net.mcreator.fnafsdecorationsport.block.FazsodablueBlock;
import net.mcreator.fnafsdecorationsport.block.FanblockonBlock;
import net.mcreator.fnafsdecorationsport.block.FanblockBlock;
import net.mcreator.fnafsdecorationsport.block.FNaF1wallmiddle3Block;
import net.mcreator.fnafsdecorationsport.block.FNaF1walldown2Block;
import net.mcreator.fnafsdecorationsport.block.EmergencyLightOnBlock;
import net.mcreator.fnafsdecorationsport.block.EmergencyLightBlock;
import net.mcreator.fnafsdecorationsport.block.DeskpropsBlock;
import net.mcreator.fnafsdecorationsport.block.CurtainredblockpanelBlock;
import net.mcreator.fnafsdecorationsport.block.CurtainredblockBlock;
import net.mcreator.fnafsdecorationsport.block.Curtainred2blockpanelBlock;
import net.mcreator.fnafsdecorationsport.block.Curtainred2blockBlock;
import net.mcreator.fnafsdecorationsport.block.CurtainpurpleblockpanelBlock;
import net.mcreator.fnafsdecorationsport.block.CurtainpurpleblockBlock;
import net.mcreator.fnafsdecorationsport.block.Curtainpurple2blockpanelBlock;
import net.mcreator.fnafsdecorationsport.block.Curtainpurple2blockBlock;
import net.mcreator.fnafsdecorationsport.block.Curtain5Block;
import net.mcreator.fnafsdecorationsport.block.Curtain4Block;
import net.mcreator.fnafsdecorationsport.block.Curtain3Block;
import net.mcreator.fnafsdecorationsport.block.Curtain2Block;
import net.mcreator.fnafsdecorationsport.block.Curtain1Block;
import net.mcreator.fnafsdecorationsport.block.CupcakeBlock;
import net.mcreator.fnafsdecorationsport.block.ChicasMagicRainbowBlock;
import net.mcreator.fnafsdecorationsport.block.ChicasMagicRainbow2Block;
import net.mcreator.fnafsdecorationsport.block.ChicaplushBlock;
import net.mcreator.fnafsdecorationsport.block.ChicabetaplushBlock;
import net.mcreator.fnafsdecorationsport.block.Box3Block;
import net.mcreator.fnafsdecorationsport.block.Box2Block;
import net.mcreator.fnafsdecorationsport.block.Box1Block;
import net.mcreator.fnafsdecorationsport.block.BonnieplushBlock;
import net.mcreator.fnafsdecorationsport.block.BobbleheadsBlock;
import net.mcreator.fnafsdecorationsport.block.Bluearcadefloor1stairsBlock;
import net.mcreator.fnafsdecorationsport.block.Bluearcadefloor1slabBlock;
import net.mcreator.fnafsdecorationsport.block.BloodTrailBlock;
import net.mcreator.fnafsdecorationsport.block.BlockgiftBlock;
import net.mcreator.fnafsdecorationsport.block.BlackdoorBlock;
import net.mcreator.fnafsdecorationsport.block.BirthdayCakeBlock;
import net.mcreator.fnafsdecorationsport.block.BattingtonwallyellowBlock;
import net.mcreator.fnafsdecorationsport.block.BattingtonwallwhitetilesBlock;
import net.mcreator.fnafsdecorationsport.block.BattingtonwalltopBlock;
import net.mcreator.fnafsdecorationsport.block.BattingtonwalltileswhiteBlock;
import net.mcreator.fnafsdecorationsport.block.BattingtonwalltilesBlock;
import net.mcreator.fnafsdecorationsport.block.Battingtonwalltiles2Block;
import net.mcreator.fnafsdecorationsport.block.BattingtonwallredBlock;
import net.mcreator.fnafsdecorationsport.block.BattingtonwallpurpleBlock;
import net.mcreator.fnafsdecorationsport.block.BattingtonwalldownredBlock;
import net.mcreator.fnafsdecorationsport.block.BattingtonwalldownBlock;
import net.mcreator.fnafsdecorationsport.block.BattingtonfloorBlock;
import net.mcreator.fnafsdecorationsport.block.Battingtonfloor7Block;
import net.mcreator.fnafsdecorationsport.block.Battingtonfloor6Block;
import net.mcreator.fnafsdecorationsport.block.Battingtonfloor5Block;
import net.mcreator.fnafsdecorationsport.block.Battingtonfloor4Block;
import net.mcreator.fnafsdecorationsport.block.Battingtonfloor3Block;
import net.mcreator.fnafsdecorationsport.block.Battingtonfloor2Block;
import net.mcreator.fnafsdecorationsport.block.BalloonsBlock;
import net.mcreator.fnafsdecorationsport.block.Balloons3Block;
import net.mcreator.fnafsdecorationsport.block.Balloons2Block;
import net.mcreator.fnafsdecorationsport.block.Arcadefloor3Block;
import net.mcreator.fnafsdecorationsport.block.Arcadefloor2Block;
import net.mcreator.fnafsdecorationsport.block.Arcadefloor1Block;
import net.mcreator.fnafsdecorationsport.block.ArcadeSignBlock;
import net.mcreator.fnafsdecorationsport.block.AlarmClockBlock;
import net.mcreator.fnafsdecorationsport.FdMod;

public class FdModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, FdMod.MODID);
	public static final RegistryObject<Block> FNAF_1WALLUP = REGISTRY.register("fnaf_1wallup", () -> new Fnaf1wallupBlock());
	public static final RegistryObject<Block> FNAF_1WALLDECO_1 = REGISTRY.register("fnaf_1walldeco_1", () -> new Fnaf1walldeco1Block());
	public static final RegistryObject<Block> FNAF_1WALLDECO_2 = REGISTRY.register("fnaf_1walldeco_2", () -> new Fnaf1walldeco2Block());
	public static final RegistryObject<Block> FNAFWALLMIDDLE_2 = REGISTRY.register("fnafwallmiddle_2", () -> new Fnafwallmiddle2Block());
	public static final RegistryObject<Block> FNAF_1WALLMIDDLE_1 = REGISTRY.register("fnaf_1wallmiddle_1", () -> new Fnaf1wallmiddle1Block());
	public static final RegistryObject<Block> F_NA_F_1WALLMIDDLE_3 = REGISTRY.register("f_na_f_1wallmiddle_3", () -> new FNaF1wallmiddle3Block());
	public static final RegistryObject<Block> FNAF_1WALLMIDDLE_4 = REGISTRY.register("fnaf_1wallmiddle_4", () -> new Fnaf1wallmiddle4Block());
	public static final RegistryObject<Block> FNAF_1WALLMIDDLE_5 = REGISTRY.register("fnaf_1wallmiddle_5", () -> new Fnaf1wallmiddle5Block());
	public static final RegistryObject<Block> FNAF_1WALLDOWN_1 = REGISTRY.register("fnaf_1walldown_1", () -> new Fnaf1walldown1Block());
	public static final RegistryObject<Block> F_NA_F_1WALLDOWN_2 = REGISTRY.register("f_na_f_1walldown_2", () -> new FNaF1walldown2Block());
	public static final RegistryObject<Block> FNAF_1WALLBATHROOM = REGISTRY.register("fnaf_1wallbathroom", () -> new Fnaf1wallbathroomBlock());
	public static final RegistryObject<Block> FNAF_1WALLBATHROOM_2 = REGISTRY.register("fnaf_1wallbathroom_2", () -> new Fnaf1wallbathroom2Block());
	public static final RegistryObject<Block> FNAF_1WALLBATHROOM_3 = REGISTRY.register("fnaf_1wallbathroom_3", () -> new Fnaf1wallbathroom3Block());
	public static final RegistryObject<Block> STAGEUP = REGISTRY.register("stageup", () -> new StageupBlock());
	public static final RegistryObject<Block> STAGEMIDDLE_1 = REGISTRY.register("stagemiddle_1", () -> new Stagemiddle1Block());
	public static final RegistryObject<Block> STAGETILES = REGISTRY.register("stagetiles", () -> new StagetilesBlock());
	public static final RegistryObject<Block> STAGETILES_2 = REGISTRY.register("stagetiles_2", () -> new Stagetiles2Block());
	public static final RegistryObject<Block> STAGETILES_3 = REGISTRY.register("stagetiles_3", () -> new Stagetiles3Block());
	public static final RegistryObject<Block> STAGEDOWN = REGISTRY.register("stagedown", () -> new StagedownBlock());
	public static final RegistryObject<Block> STAGEBLOCK_4 = REGISTRY.register("stageblock_4", () -> new Stageblock4Block());
	public static final RegistryObject<Block> STAGEBLOCK_1 = REGISTRY.register("stageblock_1", () -> new Stageblock1Block());
	public static final RegistryObject<Block> STAGEBLOCK_2 = REGISTRY.register("stageblock_2", () -> new Stageblock2Block());
	public static final RegistryObject<Block> STAGEBLOCK_3 = REGISTRY.register("stageblock_3", () -> new Stageblock3Block());
	public static final RegistryObject<Block> FNAF_2WALLUP_2 = REGISTRY.register("fnaf_2wallup_2", () -> new Fnaf2wallup2Block());
	public static final RegistryObject<Block> FNAF_2WALLUP_1 = REGISTRY.register("fnaf_2wallup_1", () -> new Fnaf2wallup1Block());
	public static final RegistryObject<Block> FNAF_2WALLMIDDLE_3 = REGISTRY.register("fnaf_2wallmiddle_3", () -> new Fnaf2wallmiddle3Block());
	public static final RegistryObject<Block> FNAF_2WALLMIDDLE_2 = REGISTRY.register("fnaf_2wallmiddle_2", () -> new Fnaf2wallmiddle2Block());
	public static final RegistryObject<Block> FNAF_2WALLMIDDLE_1 = REGISTRY.register("fnaf_2wallmiddle_1", () -> new Fnaf2wallmiddle1Block());
	public static final RegistryObject<Block> FNAF_2WALLDOWN_1 = REGISTRY.register("fnaf_2walldown_1", () -> new Fnaf2walldown1Block());
	public static final RegistryObject<Block> WHITEROOF = REGISTRY.register("whiteroof", () -> new WhiteroofBlock());
	public static final RegistryObject<Block> ROOF_1 = REGISTRY.register("roof_1", () -> new Roof1Block());
	public static final RegistryObject<Block> ROOF_2 = REGISTRY.register("roof_2", () -> new Roof2Block());
	public static final RegistryObject<Block> FFDFLOOR = REGISTRY.register("ffdfloor", () -> new FfdfloorBlock());
	public static final RegistryObject<Block> FLOORFFDSTAIRS = REGISTRY.register("floorffdstairs", () -> new FloorffdstairsBlock());
	public static final RegistryObject<Block> FLOORFFDSLAB = REGISTRY.register("floorffdslab", () -> new FloorffdslabBlock());
	public static final RegistryObject<Block> FLOORRED = REGISTRY.register("floorred", () -> new FloorredBlock());
	public static final RegistryObject<Block> FLOORREDSTAIRS = REGISTRY.register("floorredstairs", () -> new FloorredstairsBlock());
	public static final RegistryObject<Block> FLOORREDSLAB = REGISTRY.register("floorredslab", () -> new FloorredslabBlock());
	public static final RegistryObject<Block> FLOORBLUE = REGISTRY.register("floorblue", () -> new FloorblueBlock());
	public static final RegistryObject<Block> FLOORBLUESTAIRS = REGISTRY.register("floorbluestairs", () -> new FloorbluestairsBlock());
	public static final RegistryObject<Block> FLOORBLUESLAB = REGISTRY.register("floorblueslab", () -> new FloorblueslabBlock());
	public static final RegistryObject<Block> FLOORREDBLUE = REGISTRY.register("floorredblue", () -> new FloorredblueBlock());
	public static final RegistryObject<Block> FLOORREDNBLUESTAIRS = REGISTRY.register("floorrednbluestairs", () -> new FloorrednbluestairsBlock());
	public static final RegistryObject<Block> FLOORREDNBLUESLAB = REGISTRY.register("floorrednblueslab", () -> new FloorrednblueslabBlock());
	public static final RegistryObject<Block> FLOORWHITE = REGISTRY.register("floorwhite", () -> new FloorwhiteBlock());
	public static final RegistryObject<Block> FLOORWHITESTAIRS = REGISTRY.register("floorwhitestairs", () -> new FloorwhitestairsBlock());
	public static final RegistryObject<Block> FLOORWHITESLAB = REGISTRY.register("floorwhiteslab", () -> new FloorwhiteslabBlock());
	public static final RegistryObject<Block> FFDINTERIORWALLUP = REGISTRY.register("ffdinteriorwallup", () -> new FfdinteriorwallupBlock());
	public static final RegistryObject<Block> FFDINTERIORWALLMIDDLE = REGISTRY.register("ffdinteriorwallmiddle", () -> new FfdinteriorwallmiddleBlock());
	public static final RegistryObject<Block> FFDINTERIORWALLTILES = REGISTRY.register("ffdinteriorwalltiles", () -> new FfdinteriorwalltilesBlock());
	public static final RegistryObject<Block> FFDINTERIORWALLDOWN = REGISTRY.register("ffdinteriorwalldown", () -> new FfdinteriorwalldownBlock());
	public static final RegistryObject<Block> FFDEXTERIORWALLUP = REGISTRY.register("ffdexteriorwallup", () -> new FfdexteriorwallupBlock());
	public static final RegistryObject<Block> FFDEXTERIORWALLMIDDLE = REGISTRY.register("ffdexteriorwallmiddle", () -> new FfdexteriorwallmiddleBlock());
	public static final RegistryObject<Block> FFDEXTERIORWALLTILES = REGISTRY.register("ffdexteriorwalltiles", () -> new FfdexteriorwalltilesBlock());
	public static final RegistryObject<Block> FFDEXTERIORWALLDOWN = REGISTRY.register("ffdexteriorwalldown", () -> new FfdexteriorwalldownBlock());
	public static final RegistryObject<Block> FNAFMOVIEWALLUPPEREXTERIOR = REGISTRY.register("fnafmoviewallupperexterior", () -> new FnafmoviewallupperexteriorBlock());
	public static final RegistryObject<Block> FNAFMOVIEWALLUPPER_2EXTERIOR = REGISTRY.register("fnafmoviewallupper_2exterior", () -> new Fnafmoviewallupper2exteriorBlock());
	public static final RegistryObject<Block> FNAFMOVIEWALLMIDDLE_2EXTERIOR = REGISTRY.register("fnafmoviewallmiddle_2exterior", () -> new Fnafmoviewallmiddle2exteriorBlock());
	public static final RegistryObject<Block> FNAFMOVIEWALLMIDDLEEXTERIOR = REGISTRY.register("fnafmoviewallmiddleexterior", () -> new FnafmoviewallmiddleexteriorBlock());
	public static final RegistryObject<Block> FNAFMOVIEWALLBOTTOMEXTERIOR = REGISTRY.register("fnafmoviewallbottomexterior", () -> new FnafmoviewallbottomexteriorBlock());
	public static final RegistryObject<Block> REDARCADEFLOOR_1STAIRS = REGISTRY.register("redarcadefloor_1stairs", () -> new Redarcadefloor1stairsBlock());
	public static final RegistryObject<Block> REDARCADEFLOOR_1SLAB = REGISTRY.register("redarcadefloor_1slab", () -> new Redarcadefloor1slabBlock());
	public static final RegistryObject<Block> BLUEARCADEFLOOR_1STAIRS = REGISTRY.register("bluearcadefloor_1stairs", () -> new Bluearcadefloor1stairsBlock());
	public static final RegistryObject<Block> BLUEARCADEFLOOR_1SLAB = REGISTRY.register("bluearcadefloor_1slab", () -> new Bluearcadefloor1slabBlock());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKPURPLE = REGISTRY.register("piratecovecurtainblockpurple", () -> new PiratecovecurtainblockpurpleBlock());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKBLUE = REGISTRY.register("piratecovecurtainblockblue", () -> new PiratecovecurtainblockblueBlock());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKRED = REGISTRY.register("piratecovecurtainblockred", () -> new PiratecovecurtainblockredBlock());
	public static final RegistryObject<Block> CURTAINPURPLEBLOCKPANEL = REGISTRY.register("curtainpurpleblockpanel", () -> new CurtainpurpleblockpanelBlock());
	public static final RegistryObject<Block> CURTAINREDBLOCKPANEL = REGISTRY.register("curtainredblockpanel", () -> new CurtainredblockpanelBlock());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKPURPLEBLOCK = REGISTRY.register("piratecovecurtainblockpurpleblock", () -> new PiratecovecurtainblockpurpleblockBlock());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKBLUEBLOCK = REGISTRY.register("piratecovecurtainblockblueblock", () -> new PiratecovecurtainblockblueblockBlock());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKREDBLOCK = REGISTRY.register("piratecovecurtainblockredblock", () -> new PiratecovecurtainblockredblockBlock());
	public static final RegistryObject<Block> CURTAINPURPLEBLOCK = REGISTRY.register("curtainpurpleblock", () -> new CurtainpurpleblockBlock());
	public static final RegistryObject<Block> CURTAINREDBLOCK = REGISTRY.register("curtainredblock", () -> new CurtainredblockBlock());
	public static final RegistryObject<Block> ARCADEFLOOR_1 = REGISTRY.register("arcadefloor_1", () -> new Arcadefloor1Block());
	public static final RegistryObject<Block> REDARCADEFLOOR_1 = REGISTRY.register("redarcadefloor_1", () -> new Redarcadefloor1Block());
	public static final RegistryObject<Block> PIZZERIALIGHTOFF = REGISTRY.register("pizzerialightoff", () -> new PizzerialightoffBlock());
	public static final RegistryObject<Block> TRASH_1 = REGISTRY.register("trash_1", () -> new Trash1Block());
	public static final RegistryObject<Block> BLOCKGIFT = REGISTRY.register("blockgift", () -> new BlockgiftBlock());
	public static final RegistryObject<Block> WALLPAPERS = REGISTRY.register("wallpapers", () -> new WallpapersBlock());
	public static final RegistryObject<Block> WALLPAPER_1 = REGISTRY.register("wallpaper_1", () -> new Wallpaper1Block());
	public static final RegistryObject<Block> BATTINGTONWALLTOP = REGISTRY.register("battingtonwalltop", () -> new BattingtonwalltopBlock());
	public static final RegistryObject<Block> STARS_1 = REGISTRY.register("stars_1", () -> new Stars1Block());
	public static final RegistryObject<Block> BATTINGTONWALLYELLOW = REGISTRY.register("battingtonwallyellow", () -> new BattingtonwallyellowBlock());
	public static final RegistryObject<Block> WALLSTRUCTURE = REGISTRY.register("wallstructure", () -> new WallstructureBlock());
	public static final RegistryObject<Block> BATTINGTONWALLTILES_1 = REGISTRY.register("battingtonwalltiles_1", () -> new BattingtonwalltilesBlock());
	public static final RegistryObject<Block> STAGESPEAKER = REGISTRY.register("stagespeaker", () -> new StagespeakerBlock());
	public static final RegistryObject<Block> BATTINGTONWALLTILES_2 = REGISTRY.register("battingtonwalltiles_2", () -> new Battingtonwalltiles2Block());
	public static final RegistryObject<Block> ROOFWIRES_1 = REGISTRY.register("roofwires_1", () -> new Roofwires1Block());
	public static final RegistryObject<Block> BATTINGTONWALLDOWN = REGISTRY.register("battingtonwalldown", () -> new BattingtonwalldownBlock());
	public static final RegistryObject<Block> CURTAIN_1 = REGISTRY.register("curtain_1", () -> new Curtain1Block());
	public static final RegistryObject<Block> BATTINGTONWALLDOWNRED = REGISTRY.register("battingtonwalldownred", () -> new BattingtonwalldownredBlock());
	public static final RegistryObject<Block> POSTER_1 = REGISTRY.register("poster_1", () -> new Poster1Block());
	public static final RegistryObject<Block> BATTINGTONWALLPURPLE = REGISTRY.register("battingtonwallpurple", () -> new BattingtonwallpurpleBlock());
	public static final RegistryObject<Block> OFFICEWINDOW = REGISTRY.register("officewindow", () -> new OfficewindowBlock());
	public static final RegistryObject<Block> BATTINGTONWALLRED = REGISTRY.register("battingtonwallred", () -> new BattingtonwallredBlock());
	public static final RegistryObject<Block> OFFICEPOSTER = REGISTRY.register("officeposter", () -> new OfficeposterBlock());
	public static final RegistryObject<Block> BATTINGTONWALLWHITETILES = REGISTRY.register("battingtonwallwhitetiles", () -> new BattingtonwallwhitetilesBlock());
	public static final RegistryObject<Block> PIZZERIASIGNS_1 = REGISTRY.register("pizzeriasigns_1", () -> new Pizzeriasigns1Block());
	public static final RegistryObject<Block> BATTINGTONWALLTILESWHITE = REGISTRY.register("battingtonwalltileswhite", () -> new BattingtonwalltileswhiteBlock());
	public static final RegistryObject<Block> FLOORWIRES_1 = REGISTRY.register("floorwires_1", () -> new Floorwires1Block());
	public static final RegistryObject<Block> PARTYKIDSCHAIRBLUE = REGISTRY.register("partykidschairblue", () -> new PartykidschairblueBlock());
	public static final RegistryObject<Block> PARTYKIDSCHAIRRED = REGISTRY.register("partykidschairred", () -> new PartykidschairredBlock());
	public static final RegistryObject<Block> PARTYKIDSCHAIRBLACK = REGISTRY.register("partykidschairblack", () -> new PartykidschairblackBlock());
	public static final RegistryObject<Block> PARTYKIDSCHAIRPURPLE = REGISTRY.register("partykidschairpurple", () -> new PartykidschairpurpleBlock());
	public static final RegistryObject<Block> OFFICELAMP = REGISTRY.register("officelamp", () -> new OfficelampBlock());
	public static final RegistryObject<Block> STAGESUN = REGISTRY.register("stagesun", () -> new StagesunBlock());
	public static final RegistryObject<Block> STAGECLOUDS = REGISTRY.register("stageclouds", () -> new StagecloudsBlock());
	public static final RegistryObject<Block> PIRATECOVESIGN_1 = REGISTRY.register("piratecovesign_1", () -> new Piratecovesign1Block());
	public static final RegistryObject<Block> SUPPLYROOMSHELVES = REGISTRY.register("supplyroomshelves", () -> new SupplyroomshelvesBlock());
	public static final RegistryObject<Block> FANBLOCK = REGISTRY.register("fanblock", () -> new FanblockBlock());
	public static final RegistryObject<Block> FANBLOCKON = REGISTRY.register("fanblockon", () -> new FanblockonBlock());
	public static final RegistryObject<Block> DESKPROPS = REGISTRY.register("deskprops", () -> new DeskpropsBlock());
	public static final RegistryObject<Block> ONLYOFFICEDESK = REGISTRY.register("onlyofficedesk", () -> new OnlyofficedeskBlock());
	public static final RegistryObject<Block> MONITORS_1 = REGISTRY.register("monitors_1", () -> new Monitors1Block());
	public static final RegistryObject<Block> OFFICEDESK = REGISTRY.register("officedesk", () -> new OfficedeskBlock());
	public static final RegistryObject<Block> OFFICECHAIR = REGISTRY.register("officechair", () -> new OfficechairBlock());
	public static final RegistryObject<Block> OFFICELIGHTOFF = REGISTRY.register("officelightoff", () -> new OfficelightoffBlock());
	public static final RegistryObject<Block> OFFICEDOORBLOCKOPEN = REGISTRY.register("officedoorblockopen", () -> new OfficedoorblockopenBlock());
	public static final RegistryObject<Block> OFFICELIGHTBUTTONOFF = REGISTRY.register("officelightbuttonoff", () -> new OfficelightbuttonoffBlock());
	public static final RegistryObject<Block> OFFICEDOORBUTTONOFF = REGISTRY.register("officedoorbuttonoff", () -> new OfficedoorbuttonoffBlock());
	public static final RegistryObject<Block> PARTYHATRED = REGISTRY.register("partyhatred", () -> new PartyhatredBlock());
	public static final RegistryObject<Block> WALLWARNINGSIGN = REGISTRY.register("wallwarningsign", () -> new WallwarningsignBlock());
	public static final RegistryObject<Block> FAZSODARED = REGISTRY.register("fazsodared", () -> new FazsodaredBlock());
	public static final RegistryObject<Block> FAZSODABLUE = REGISTRY.register("fazsodablue", () -> new FazsodablueBlock());
	public static final RegistryObject<Block> SHELF_1 = REGISTRY.register("shelf_1", () -> new Shelf1Block());
	public static final RegistryObject<Block> BLACKDOOR = REGISTRY.register("blackdoor", () -> new BlackdoorBlock());
	public static final RegistryObject<Block> REDDOOR = REGISTRY.register("reddoor", () -> new ReddoorBlock());
	public static final RegistryObject<Block> PIZZERIA_LIGHT_ON = REGISTRY.register("pizzeria_light_on", () -> new Pizzerialight1Block());
	public static final RegistryObject<Block> CURTAIN_3 = REGISTRY.register("curtain_3", () -> new Curtain3Block());
	public static final RegistryObject<Block> CURTAIN_4 = REGISTRY.register("curtain_4", () -> new Curtain4Block());
	public static final RegistryObject<Block> CURTAIN_5 = REGISTRY.register("curtain_5", () -> new Curtain5Block());
	public static final RegistryObject<Block> WALLPAPERS_2 = REGISTRY.register("wallpapers_2", () -> new Wallpapers2Block());
	public static final RegistryObject<Block> WALLPAPERS_3 = REGISTRY.register("wallpapers_3", () -> new Wallpapers3Block());
	public static final RegistryObject<Block> STARS_2 = REGISTRY.register("stars_2", () -> new Stars2Block());
	public static final RegistryObject<Block> STARS_3 = REGISTRY.register("stars_3", () -> new Stars3Block());
	public static final RegistryObject<Block> MONITORS_2 = REGISTRY.register("monitors_2", () -> new Monitors2Block());
	public static final RegistryObject<Block> MONITORS_3 = REGISTRY.register("monitors_3", () -> new Monitors3Block());
	public static final RegistryObject<Block> MONITORS_4 = REGISTRY.register("monitors_4", () -> new Monitors4Block());
	public static final RegistryObject<Block> GIFTBLUE = REGISTRY.register("giftblue", () -> new GiftblueBlock());
	public static final RegistryObject<Block> GIFTGREEN = REGISTRY.register("giftgreen", () -> new GiftgreenBlock());
	public static final RegistryObject<Block> GIFTYELLOW = REGISTRY.register("giftyellow", () -> new GiftyellowBlock());
	public static final RegistryObject<Block> GIFTPURPLE = REGISTRY.register("giftpurple", () -> new GiftpurpleBlock());
	public static final RegistryObject<Block> ROOFWIRES_2 = REGISTRY.register("roofwires_2", () -> new Roofwires2Block());
	public static final RegistryObject<Block> ROOFWIRES_4 = REGISTRY.register("roofwires_4", () -> new Roofwires4Block());
	public static final RegistryObject<Block> ROOFWIRES_3 = REGISTRY.register("roofwires_3", () -> new Roofwires3Block());
	public static final RegistryObject<Block> ROOFWIRES_5 = REGISTRY.register("roofwires_5", () -> new Roofwires5Block());
	public static final RegistryObject<Block> CURTAIN_2 = REGISTRY.register("curtain_2", () -> new Curtain2Block());
	public static final RegistryObject<Block> TRASH_2 = REGISTRY.register("trash_2", () -> new Trash2Block());
	public static final RegistryObject<Block> TRASH_3 = REGISTRY.register("trash_3", () -> new Trash3Block());
	public static final RegistryObject<Block> OFFICEDOORBUTTONON = REGISTRY.register("officedoorbuttonon", () -> new OfficedoorbuttononBlock());
	public static final RegistryObject<Block> FLOORWIRES_2 = REGISTRY.register("floorwires_2", () -> new Floorwires2Block());
	public static final RegistryObject<Block> FLOORWIRES_3 = REGISTRY.register("floorwires_3", () -> new Floorwires3Block());
	public static final RegistryObject<Block> CURTAINRED_2BLOCK = REGISTRY.register("curtainred_2block", () -> new Curtainred2blockBlock());
	public static final RegistryObject<Block> CURTAINPURPLE_2BLOCK = REGISTRY.register("curtainpurple_2block", () -> new Curtainpurple2blockBlock());
	public static final RegistryObject<Block> CURTAINRED_2BLOCKPANEL = REGISTRY.register("curtainred_2blockpanel", () -> new Curtainred2blockpanelBlock());
	public static final RegistryObject<Block> CURTAINPURPLE_2BLOCKPANEL = REGISTRY.register("curtainpurple_2blockpanel", () -> new Curtainpurple2blockpanelBlock());
	public static final RegistryObject<Block> PIRATECOVESIGN_2 = REGISTRY.register("piratecovesign_2", () -> new Piratecovesign2Block());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKRED_2 = REGISTRY.register("piratecovecurtainblockred_2", () -> new Piratecovecurtainblockred2Block());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKRED_3 = REGISTRY.register("piratecovecurtainblockred_3", () -> new Piratecovecurtainblockred3Block());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKPURPLE_2 = REGISTRY.register("piratecovecurtainblockpurple_2", () -> new Piratecovecurtainblockpurple2Block());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKPURPLE_3 = REGISTRY.register("piratecovecurtainblockpurple_3", () -> new Piratecovecurtainblockpurple3Block());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKBLUE_2 = REGISTRY.register("piratecovecurtainblockblue_2", () -> new Piratecovecurtainblockblue2Block());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKBLUE_3 = REGISTRY.register("piratecovecurtainblockblue_3", () -> new Piratecovecurtainblockblue3Block());
	public static final RegistryObject<Block> ARCADEFLOOR_2 = REGISTRY.register("arcadefloor_2", () -> new Arcadefloor2Block());
	public static final RegistryObject<Block> ARCADEFLOOR_3 = REGISTRY.register("arcadefloor_3", () -> new Arcadefloor3Block());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKREDBLOCK_2 = REGISTRY.register("piratecovecurtainblockredblock_2", () -> new Piratecovecurtainblockredblock2Block());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKBLUEBLOCK_2 = REGISTRY.register("piratecovecurtainblockblueblock_2", () -> new Piratecovecurtainblockblueblock2Block());
	public static final RegistryObject<Block> PIRATECOVECURTAINBLOCKPURPLEBLOCK_2 = REGISTRY.register("piratecovecurtainblockpurpleblock_2", () -> new Piratecovecurtainblockpurpleblock2Block());
	public static final RegistryObject<Block> OFFICELIGHTBUTTONON = REGISTRY.register("officelightbuttonon", () -> new OfficelightbuttononBlock());
	public static final RegistryObject<Block> OFFICEDOORBLOCK = REGISTRY.register("officedoorblock", () -> new OfficedoorblockBlock());
	public static final RegistryObject<Block> OFFICELIGHTON = REGISTRY.register("officelighton", () -> new OfficelightonBlock());
	public static final RegistryObject<Block> PARTYHATGREEN = REGISTRY.register("partyhatgreen", () -> new PartyhatgreenBlock());
	public static final RegistryObject<Block> PARTYHATBLUE = REGISTRY.register("partyhatblue", () -> new PartyhatblueBlock());
	public static final RegistryObject<Block> PARTYHATPURPLE = REGISTRY.register("partyhatpurple", () -> new PartyhatpurpleBlock());
	public static final RegistryObject<Block> PIZZERIASIGNS_2 = REGISTRY.register("pizzeriasigns_2", () -> new Pizzeriasigns2Block());
	public static final RegistryObject<Block> PIZZERIASIGNS_3 = REGISTRY.register("pizzeriasigns_3", () -> new Pizzeriasigns3Block());
	public static final RegistryObject<Block> PIZZERIASIGNS_4 = REGISTRY.register("pizzeriasigns_4", () -> new Pizzeriasigns4Block());
	public static final RegistryObject<Block> WALLPAPER_2 = REGISTRY.register("wallpaper_2", () -> new Wallpaper2Block());
	public static final RegistryObject<Block> WALLPAPER_3 = REGISTRY.register("wallpaper_3", () -> new Wallpaper3Block());
	public static final RegistryObject<Block> WALLPAPER_4 = REGISTRY.register("wallpaper_4", () -> new Wallpaper4Block());
	public static final RegistryObject<Block> WALLPAPERS_4 = REGISTRY.register("wallpapers_4", () -> new Wallpapers4Block());
	public static final RegistryObject<Block> REDARCADEFLOOR_2 = REGISTRY.register("redarcadefloor_2", () -> new Redarcadefloor2Block());
	public static final RegistryObject<Block> REDARCADEFLOOR_3 = REGISTRY.register("redarcadefloor_3", () -> new Redarcadefloor3Block());
	public static final RegistryObject<Block> SHELF_2 = REGISTRY.register("shelf_2", () -> new Shelf2Block());
	public static final RegistryObject<Block> ALARM_CLOCK = REGISTRY.register("alarm_clock", () -> new AlarmClockBlock());
	public static final RegistryObject<Block> ARCADE_SIGN = REGISTRY.register("arcade_sign", () -> new ArcadeSignBlock());
	public static final RegistryObject<Block> BLOOD_TRAIL = REGISTRY.register("blood_trail", () -> new BloodTrailBlock());
	public static final RegistryObject<Block> CHICAS_MAGIC_RAINBOW = REGISTRY.register("chicas_magic_rainbow", () -> new ChicasMagicRainbowBlock());
	public static final RegistryObject<Block> CHICAS_MAGIC_RAINBOW_2 = REGISTRY.register("chicas_magic_rainbow_2", () -> new ChicasMagicRainbow2Block());
	public static final RegistryObject<Block> MAGIC_RAINBOW_3 = REGISTRY.register("magic_rainbow_3", () -> new MagicRainbow3Block());
	public static final RegistryObject<Block> MAGICRAINBOW_4 = REGISTRY.register("magicrainbow_4", () -> new Magicrainbow4Block());
	public static final RegistryObject<Block> MAGURANBO_5 = REGISTRY.register("maguranbo_5", () -> new Maguranbo5Block());
	public static final RegistryObject<Block> FNAF_2WALLMIDDLECONFETTI = REGISTRY.register("fnaf_2wallmiddleconfetti", () -> new Fnaf2wallmiddleconfettiBlock());
	public static final RegistryObject<Block> PURPLESTAGEBRICKS = REGISTRY.register("purplestagebricks", () -> new PurplestagebricksBlock());
	public static final RegistryObject<Block> FNAF_2STAGEWALLMIDDLE = REGISTRY.register("fnaf_2stagewallmiddle", () -> new Fnaf2stagewallmiddleBlock());
	public static final RegistryObject<Block> FNAF_2STAGEWALLTILES = REGISTRY.register("fnaf_2stagewalltiles", () -> new Fnaf2stagewalltilesBlock());
	public static final RegistryObject<Block> BALLOONS = REGISTRY.register("balloons", () -> new BalloonsBlock());
	public static final RegistryObject<Block> BALLOONS_2 = REGISTRY.register("balloons_2", () -> new Balloons2Block());
	public static final RegistryObject<Block> BALLOONS_3 = REGISTRY.register("balloons_3", () -> new Balloons3Block());
	public static final RegistryObject<Block> BOBBLEHEADS = REGISTRY.register("bobbleheads", () -> new BobbleheadsBlock());
	public static final RegistryObject<Block> BIRTHDAY_CAKE = REGISTRY.register("birthday_cake", () -> new BirthdayCakeBlock());
	public static final RegistryObject<Block> EMERGENCY_LIGHT = REGISTRY.register("emergency_light", () -> new EmergencyLightBlock());
	public static final RegistryObject<Block> EMERGENCY_LIGHT_ON = REGISTRY.register("emergency_light_on", () -> new EmergencyLightOnBlock());
	public static final RegistryObject<Block> WALLPOSTERFACESF = REGISTRY.register("wallposterfacesf", () -> new WallposterfacesfBlock());
	public static final RegistryObject<Block> WALLPOSTERFACESC = REGISTRY.register("wallposterfacesc", () -> new WallposterfacescBlock());
	public static final RegistryObject<Block> WALLPOSTERFACESB = REGISTRY.register("wallposterfacesb", () -> new WallposterfacesbBlock());
	public static final RegistryObject<Block> FFDWALLPOSTERFACES_1 = REGISTRY.register("ffdwallposterfaces_1", () -> new Ffdwallposterfaces1Block());
	public static final RegistryObject<Block> FFDWALLPOSTERFACES_2 = REGISTRY.register("ffdwallposterfaces_2", () -> new Ffdwallposterfaces2Block());
	public static final RegistryObject<Block> CHICAPLUSH = REGISTRY.register("chicaplush", () -> new ChicaplushBlock());
	public static final RegistryObject<Block> CHICABETAPLUSH = REGISTRY.register("chicabetaplush", () -> new ChicabetaplushBlock());
	public static final RegistryObject<Block> FREDDYPLUSH = REGISTRY.register("freddyplush", () -> new FreddyplushBlock());
	public static final RegistryObject<Block> BONNIEPLUSH = REGISTRY.register("bonnieplush", () -> new BonnieplushBlock());
	public static final RegistryObject<Block> FOXYPLUSH = REGISTRY.register("foxyplush", () -> new FoxyplushBlock());
	public static final RegistryObject<Block> SPRINGBONNIEPLUSH = REGISTRY.register("springbonnieplush", () -> new SpringbonnieplushBlock());
	public static final RegistryObject<Block> GOLDENFREDDYPLUSH = REGISTRY.register("goldenfreddyplush", () -> new GoldenfreddyplushBlock());
	public static final RegistryObject<Block> FREDBEARPLUSH = REGISTRY.register("fredbearplush", () -> new FredbearplushBlock());
	public static final RegistryObject<Block> FNAFMOVIEOFFICEDOOR = REGISTRY.register("fnafmovieofficedoor", () -> new FnafmovieofficedoorBlock());
	public static final RegistryObject<Block> FNAFMOVIEBATHROOMDOOR = REGISTRY.register("fnafmoviebathroomdoor", () -> new FnafmoviebathroomdoorBlock());
	public static final RegistryObject<Block> FFDPIZZERIADOOR = REGISTRY.register("ffdpizzeriadoor", () -> new FfdpizzeriadoorBlock());
	public static final RegistryObject<Block> BATTINGTONFLOOR = REGISTRY.register("battingtonfloor", () -> new BattingtonfloorBlock());
	public static final RegistryObject<Block> BATTINGTONFLOOR_2 = REGISTRY.register("battingtonfloor_2", () -> new Battingtonfloor2Block());
	public static final RegistryObject<Block> BATTINGTONFLOOR_3 = REGISTRY.register("battingtonfloor_3", () -> new Battingtonfloor3Block());
	public static final RegistryObject<Block> BATTINGTONFLOOR_4 = REGISTRY.register("battingtonfloor_4", () -> new Battingtonfloor4Block());
	public static final RegistryObject<Block> BATTINGTONFLOOR_5 = REGISTRY.register("battingtonfloor_5", () -> new Battingtonfloor5Block());
	public static final RegistryObject<Block> BATTINGTONFLOOR_6 = REGISTRY.register("battingtonfloor_6", () -> new Battingtonfloor6Block());
	public static final RegistryObject<Block> BATTINGTONFLOOR_7 = REGISTRY.register("battingtonfloor_7", () -> new Battingtonfloor7Block());
	public static final RegistryObject<Block> SWITCHOFF = REGISTRY.register("switchoff", () -> new SwitchoffBlock());
	public static final RegistryObject<Block> SWITCHON = REGISTRY.register("switchon", () -> new SwitchonBlock());
	public static final RegistryObject<Block> FREDDY_FAZBEARTRASHCAN = REGISTRY.register("freddy_fazbeartrashcan", () -> new FreddyFazbeartrashcanBlock());
	public static final RegistryObject<Block> POLE_1 = REGISTRY.register("pole_1", () -> new Pole1Block());
	public static final RegistryObject<Block> POLE_2 = REGISTRY.register("pole_2", () -> new Pole2Block());
	public static final RegistryObject<Block> FNAF_2WALLUPPERCONFETTI = REGISTRY.register("fnaf_2wallupperconfetti", () -> new Fnaf2wallupperconfettiBlock());
	public static final RegistryObject<Block> FFDINTERIORWALLMIDDLECONFETTI_1 = REGISTRY.register("ffdinteriorwallmiddleconfetti_1", () -> new Ffdinteriorwallmiddleconfetti1Block());
	public static final RegistryObject<Block> FFDINTERIORWALLMIDDLECONFETTI_2 = REGISTRY.register("ffdinteriorwallmiddleconfetti_2", () -> new Ffdinteriorwallmiddleconfetti2Block());
	public static final RegistryObject<Block> FFDINTERIORWALLMIDDLECONFETTI_3 = REGISTRY.register("ffdinteriorwallmiddleconfetti_3", () -> new Ffdinteriorwallmiddleconfetti3Block());
	public static final RegistryObject<Block> TESTINGBLOCK = REGISTRY.register("testingblock", () -> new TestingblockBlock());
	public static final RegistryObject<Block> TABLENORTH = REGISTRY.register("tablenorth", () -> new TablenorthBlock());
	public static final RegistryObject<Block> TABLESOUTH = REGISTRY.register("tablesouth", () -> new TablesouthBlock());
	public static final RegistryObject<Block> BOX_1 = REGISTRY.register("box_1", () -> new Box1Block());
	public static final RegistryObject<Block> BOX_2 = REGISTRY.register("box_2", () -> new Box2Block());
	public static final RegistryObject<Block> BOX_3 = REGISTRY.register("box_3", () -> new Box3Block());
	public static final RegistryObject<Block> WOODENWALLREDDOWN = REGISTRY.register("woodenwallreddown", () -> new WoodenwallreddownBlock());
	public static final RegistryObject<Block> WOODENWALLREDSINGLE = REGISTRY.register("woodenwallredsingle", () -> new WoodenwallredsingleBlock());
	public static final RegistryObject<Block> WOODENWALLBROWNTILES = REGISTRY.register("woodenwallbrowntiles", () -> new WoodenwallbrowntilesBlock());
	public static final RegistryObject<Block> WOODENWALLBROWNSINGLE = REGISTRY.register("woodenwallbrownsingle", () -> new WoodenwallbrownsingleBlock());
	public static final RegistryObject<Block> WOODENWALLBROWNTOP = REGISTRY.register("woodenwallbrowntop", () -> new WoodenwallbrowntopBlock());
	public static final RegistryObject<Block> WOODENWALLBROWNTOPDIRTY = REGISTRY.register("woodenwallbrowntopdirty", () -> new WoodenwallbrowntopdirtyBlock());
	public static final RegistryObject<Block> LARGEWALLWIRES_1 = REGISTRY.register("largewallwires_1", () -> new Largewallwires1Block());
	public static final RegistryObject<Block> FLOORGREENBLUE = REGISTRY.register("floorgreenblue", () -> new FloorgreenblueBlock());
	public static final RegistryObject<Block> FLOORYELLOWBLUE = REGISTRY.register("flooryellowblue", () -> new FlooryellowblueBlock());
	public static final RegistryObject<Block> LARGEWALLWIRES_2 = REGISTRY.register("largewallwires_2", () -> new Largewallwires2Block());
	public static final RegistryObject<Block> CUPCAKE = REGISTRY.register("cupcake", () -> new CupcakeBlock());
	public static final RegistryObject<Block> LARGEWALLWIRES_3 = REGISTRY.register("largewallwires_3", () -> new Largewallwires3Block());
	public static final RegistryObject<Block> LARGEWALLSTARS_1 = REGISTRY.register("largewallstars_1", () -> new Largewallstars1Block());
	public static final RegistryObject<Block> FNAF_2WALLUPPERCONFETTI_2 = REGISTRY.register("fnaf_2wallupperconfetti_2", () -> new Fnaf2wallupperconfetti2Block());
	public static final RegistryObject<Block> LARGEWALLSTARS_2 = REGISTRY.register("largewallstars_2", () -> new Largewallstars2Block());
	public static final RegistryObject<Block> LARGEWALLSTARS_3 = REGISTRY.register("largewallstars_3", () -> new Largewallstars3Block());
	public static final RegistryObject<Block> FLOORGREENBLUESTAIR = REGISTRY.register("floorgreenbluestair", () -> new FloorgreenbluestairBlock());
	public static final RegistryObject<Block> LARGEWALLSTARS_4 = REGISTRY.register("largewallstars_4", () -> new Largewallstars4Block());
	public static final RegistryObject<Block> FLOORGREENBLUESLAB = REGISTRY.register("floorgreenblueslab", () -> new FloorgreenblueslabBlock());
	public static final RegistryObject<Block> FLOORYELLOWBLUESLAB = REGISTRY.register("flooryellowblueslab", () -> new FlooryellowblueslabBlock());
	public static final RegistryObject<Block> LARGEWALLPAPERCUTS_1 = REGISTRY.register("largewallpapercuts_1", () -> new Largewallpapercuts1Block());
	public static final RegistryObject<Block> FLOORYELLOWBLUESTAIR = REGISTRY.register("flooryellowbluestair", () -> new FlooryellowbluestairBlock());
	public static final RegistryObject<Block> LARGEWALLPAPERCUTS_2 = REGISTRY.register("largewallpapercuts_2", () -> new Largewallpapercuts2Block());
	public static final RegistryObject<Block> WHITEBLACKFLOORINVERTED = REGISTRY.register("whiteblackfloorinverted", () -> new WhiteblackfloorinvertedBlock());
	public static final RegistryObject<Block> LARGEWALLPAPERCUTS_3 = REGISTRY.register("largewallpapercuts_3", () -> new Largewallpapercuts3Block());
	public static final RegistryObject<Block> WHITEBLACKFLOORINVERTEDSLAB = REGISTRY.register("whiteblackfloorinvertedslab", () -> new WhiteblackfloorinvertedslabBlock());
	public static final RegistryObject<Block> LARGEWALLPARTYBANNERS_1 = REGISTRY.register("largewallpartybanners_1", () -> new Largewallpartybanners1Block());
	public static final RegistryObject<Block> LARGEWALLPARTYBANNERS_2 = REGISTRY.register("largewallpartybanners_2", () -> new Largewallpartybanners2Block());
	public static final RegistryObject<Block> WHITEBLACKFLOORINVERTEDSTAIR = REGISTRY.register("whiteblackfloorinvertedstair", () -> new WhiteblackfloorinvertedstairBlock());
	public static final RegistryObject<Block> LARGEWALLPARTYBANNERS_3 = REGISTRY.register("largewallpartybanners_3", () -> new Largewallpartybanners3Block());
}
